language: python
python:
  - "2.7"
  - "3.6"

install:
  - pip install cxroots
  - pip download cxroots --no-deps
  - tar -xzf cxroots-*.tar.gz
  - cd cxroots-*

script:
  - python setup.py test --addopts '-n 2'
